### PR TITLE
refactored, adding parsing

### PR DESCRIPTION
**Pull request by YafahEdelman**
Use "sudo pip install parse" to get the parse module. This should make adding more commands nicer in the future.

### CODE REVIEW

**Comment by martijnarts** [comment]
Do `pip freeze > requirements.txt` and then commit the requirements file.

**Comment by YafahEdelman** [comment]
ah, will pip freeze, and the comments are useless, were just there to clear up confusion, I'll remove them.

**Comment by YafahEdelman** [comment]
pip freeze shows everything I have installed with pip, I'll add what's needed for this update to this.

**Comment by martijnarts** [comment]
Oh right, that happens when you're not running in a virtualenv. Which you should be ;)

Also, you should [name your commits better](http://chris.beams.io/posts/git-commit/)!

**Comment by YafahEdelman** [comment]
I was doing this on a online ssh session, which didn't have access to my github account, and was too lazy to put in my username and password every time I wanted to push. Hence, I made all edits in the github text editor, which is why there are so many edits. Programming behind a proxy is annoying.

Also, all the edits are complete, and the program works.

**Comment by martijnarts** [comment]
https://help.github.com/articles/caching-your-github-password-in-git/

**Comment by Qwertie-** [comment]
Using .add/.info on its own doesn't show the usage message unless you add 2 spaces after

**Comment by Qwertie-** [comment]
Tested and works, merging now.

**Pull request merged**
